import environ
env = environ.Env()


SECRET_KEY = env.str('DJANGO_SECRET_KEY')

DEBUG = env.bool('DJANGO_DEBUG')

DATABASES = {'default': env.db('DATABASE_URL')}

ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS')

ACCOUNT_SID = env('ACCOUNT_SID')
AUTH_TOKEN = env('AUTH_TOKEN')
TW_NUMBER = env('TW_NUMBER')

BASE_URL = env('BASE_URL')
CALLBACK_BASE_URL = env('CALLBACK_BASE_URL')
MERCHANT_ID = env('MERCHANT_ID')
PAY_SECRET_KEY = env('PAY_SECRET_KEY')
